config/routes.rb
Tdt::Application.routes.draw do
  resources :characters

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :age, :alignment, :ath, :career, :con, :dex, :gender, :initiative, :int, :name, :ref, :spd, :str, :wil
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  # AngularJS automatically sends CSRF token as a header called X-XSRF
  # this makes sure rails gets it
  def verified_request?
    !protect_against_forgery? || request.get? ||
      form_authenticity_token == params[request_forgery_protection_token] ||
      form_authenticity_token == request.headers['X-XSRF-Token']
  end
 end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
respond_to :json
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])
    #session[:character_id] = @character.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :career %><br />
    <%= f.text_field :career %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :alignment %><br />
    <%= f.text_field :alignment %>
  </div>
  <div class="field">
    <%= f.label :str %><br />
    <%= f.number_field :str %>
  </div>
  <div class="field">
    <%= f.label :ref %><br />
    <%= f.number_field :ref %>
  </div>
  <div class="field">
    <%= f.label :int %><br />
    <%= f.number_field :int %>
  </div>
  <div class="field">
    <%= f.label :con %><br />
    <%= f.number_field :con %>
  </div>
  <div class="field">
    <%= f.label :wil %><br />
    <%= f.number_field :wil %>
  </div>
  <div class="field">
    <%= f.label :dex %><br />
    <%= f.number_field :dex %>
  </div>
  <div class="field">
    <%= f.label :ath %><br />
    <%= f.number_field :ath %>
  </div>
  <div class="field">
    <%= f.label :spd %><br />
    <%= f.number_field :spd %>
  </div>
  <div class="field">
    <%= f.label :initiative %><br />
    <%= f.number_field :initiative %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Career</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Alignment</th>
    <th>Str</th>
    <th>Ref</th>
    <th>Int</th>
    <th>Con</th>
    <th>Wil</th>
    <th>Dex</th>
    <th>Ath</th>
    <th>Spd</th>
    <th>Initiative</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.career %></td>
    <td><%= character.age %></td>
    <td><%= character.gender %></td>
    <td><%= character.alignment %></td>
    <td><%= character.str %></td>
    <td><%= character.ref %></td>
    <td><%= character.int %></td>
    <td><%= character.con %></td>
    <td><%= character.wil %></td>
    <td><%= character.dex %></td>
    <td><%= character.ath %></td>
    <td><%= character.spd %></td>
    <td><%= character.initiative %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Career:</b>
  <%= @character.career %>
</p>

<p>
  <b>Age:</b>
  <%= @character.age %>
</p>

<p>
  <b>Gender:</b>
  <%= @character.gender %>
</p>

<p>
  <b>Alignment:</b>
  <%= @character.alignment %>
</p>

<p>
  <b>Str:</b>
  <%= @character.str %>
</p>

<p>
  <b>Ref:</b>
  <%= @character.ref %>
</p>

<p>
  <b>Int:</b>
  <%= @character.int %>
</p>

<p>
  <b>Con:</b>
  <%= @character.con %>
</p>

<p>
  <b>Wil:</b>
  <%= @character.wil %>
</p>

<p>
  <b>Dex:</b>
  <%= @character.dex %>
</p>

<p>
  <b>Ath:</b>
  <%= @character.ath %>
</p>

<p>
  <b>Spd:</b>
  <%= @character.spd %>
</p>

<p>
  <b>Initiative:</b>
  <%= @character.initiative %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="TdtClient" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tdt" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <meta id='csrf' ng-controller="CsrfCtrl".
      data-csrf="<%= form_authenticity_token%>">

    <!-- <link href="assets/favicon.ico" rel="shortcut icon"> -->
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Tdt</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <!-- main menu models -->
<li><%= link_to 'Characters', characters_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <!-- templates load here -->
          <div ng-view class="span9"></div>
          <!-- templates load here -->
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <!-- sidebar menu models -->
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>